### PR TITLE
Add Korean translation

### PR DESCRIPTION
**Pull request by miner7222**
# WE MERGE PULL REQUESTS SUBMITTED HERE AFTER REVIEWED BY CORE DEVELOPER

If you are submitting any patches kindly wait for Core Developers to review.

You can join our community on Telegram
* [Community Group](https://t.me/pbrpcom)

* [Test Build & Build Help Group](https://t.me/pbrp_testers)

### CODE REVIEW

**Comment by manjotsidhu** [comment]
@jjhitel The current font doesn't supports Korean ?

**Comment by miner7222** [comment]
> @jjhitel The current font doesn't supports Korean ?

Yes, Korean has own special characters, which are completely different from Chinese, Japanese, and the others.

**Comment by AndroiableDroid** [comment]
@manjotsidhu That's forked before changes merged, New support support I think

**Comment by DelightReza** [comment]
@jjhitel 
 
https://ibb.co/C78WypP
Which is korean language?

**Comment by miner7222** [comment]
@raza231198 I've pushed some commits to display Korean correctly.

Screenshot_PBRP_2020-10-11-05-00-11

**Comment by DelightReza** [comment]
@jjhitel please check when you have selected English language, it's correct or not

**Review by AndroiableDroid — APPROVED** [review]

**Review by AndroiableDroid — APPROVED** [review]
Looks good to me

**Pull request merged**
