### PR TITLE
pb: Update Variables

### PR DESCRIPTION
**Pull request by DelightReza**

### CODE REVIEW

**Comment by manjotsidhu** [comment]
@AndroiableDroid

**Review by AndroiableDroid — CHANGES_REQUESTED** [review]
https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/pull/69/commits/5b9235a765d07f7aca2cd5849b56f4463bf3af3f#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR21
Here `PB_BUILD` IS not defined before either define it first or something.

**Comment by DelightReza** [comment]
> [5b9235a#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR21](https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/commit/5b9235a765d07f7aca2cd5849b56f4463bf3af3f#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR21)
> Here `PB_BUILD` IS not defined before either define it first or something.

https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/commit/5b9235a765d07f7aca2cd5849b56f4463bf3af3f#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR151 it's defined?

**Comment by manjotsidhu** [comment]
> > [5b9235a#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR21](https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/commit/5b9235a765d07f7aca2cd5849b56f4463bf3af3f#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR21)
> > Here `PB_BUILD` IS not defined before either define it first or something.
> 
> [5b9235a#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR151](https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/commit/5b9235a765d07f7aca2cd5849b56f4463bf3af3f#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR151) it's defined?

PB_BUILD is used before definition

**Comment by DelightReza** [comment]
> > > [5b9235a#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR21](https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/commit/5b9235a765d07f7aca2cd5849b56f4463bf3af3f#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR21)
> > > Here `PB_BUILD` IS not defined before either define it first or something.
> > 
> > 
> > [5b9235a#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR151](https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/commit/5b9235a765d07f7aca2cd5849b56f4463bf3af3f#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR151) it's defined?
> 
> PB_BUILD is used before definition

I have built it's working 🙄

**Comment by AndroiableDroid** [comment]
@raza231198 I need to check it no issues will letvl you know soon

**Comment by AndroiableDroid** [comment]
> > > > [5b9235a#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR21](https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/commit/5b9235a765d07f7aca2cd5849b56f4463bf3af3f#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR21)
> > > > Here `PB_BUILD` IS not defined before either define it first or something.
> > > 
> > > 
> > > [5b9235a#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR151](https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/commit/5b9235a765d07f7aca2cd5849b56f4463bf3af3f#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR151) it's defined?
> > 
> > 
> > PB_BUILD is used before definition
> 
> I have built it's working 🙄

Because you defined it the yml or board config

**Comment by DelightReza** [comment]
> > > > > [5b9235a#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR21](https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/commit/5b9235a765d07f7aca2cd5849b56f4463bf3af3f#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR21)
> > > > > Here `PB_BUILD` IS not defined before either define it first or something.
> > > > 
> > > > 
> > > > [5b9235a#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR151](https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/commit/5b9235a765d07f7aca2cd5849b56f4463bf3af3f#diff-337369197e103c5238491492684cb6675a61f729357beec782045332224cba2eR151) it's defined?
> > > 
> > > 
> > > PB_BUILD is used before definition
> > 
> > 
> > I have built it's working 🙄
> 
> Because you defined it the yml or board config

https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/pull/69/commits/5b9235a765d07f7aca2cd5849b56f4463bf3af3f#diff-8d88eb632967032ab70dc52ece6ec958fb13d818e22d3513130ae177993b2fd7R54

**Review by AndroiableDroid — APPROVED** [review]

**Review by manjotsidhu — APPROVED** [review]

**Pull request merged**
