### PR TITLE
gui: Remove SuperSU & Unroot SuperSU

### PR DESCRIPTION
**Pull request by DelightReza**

### CODE REVIEW

**Comment by manjotsidhu** [comment]
@raza231198 we also need to remove these tools from `vendor_utils`

**Review by manjotsidhu — COMMENTED** [review]
LGTM

**Comment by manjotsidhu** [comment]
@raza231198 we also need to merge these changes in `android-10.0`

**Comment by DelightReza** [comment]
> @raza231198 we also need to remove these tools from `vendor_utils`

Yey

**Comment by manjotsidhu** [comment]
Delete this as well https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/blob/b4c4575b04505b25997b0b9bf2bfb004201b49ab/gui/theme/portrait_hdpi/ui.xml#L162

**Comment by DelightReza** [comment]
> Delete this as well
> 
> https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/blob/b4c4575b04505b25997b0b9bf2bfb004201b49ab/gui/theme/portrait_hdpi/ui.xml#L162

Ok

**Review by AndroiableDroid — COMMENTED** [review]
Manual testing done?

**Comment by DelightReza** [comment]
> Manual testing done?

Yes

**Review by AndroiableDroid — APPROVED** [review]
LGTM

**Pull request merged**
