### PR TITLE
Remove SuperSU & Unroot SuperSU

### PR DESCRIPTION
**Pull request by DelightReza**

### CODE REVIEW

**Comment by AndroiableDroid** [comment]
@raza231198 Manually tested?

**Comment by manjotsidhu** [comment]
No but hopefully it should work. @AndroiableDroid if you say so we will get it tested

**Comment by AndroiableDroid** [comment]
@manjotsidhu ya

**Comment by manjotsidhu** [comment]
@AndroiableDroid 
image

**Comment by AndroiableDroid** [comment]
@manjotsidhu Tested?

**Comment by AndroiableDroid** [comment]
@AndroiableDroid Ya +2

**Review by manjotsidhu — APPROVED** [review]
LGTM

**Pull request merged**
