### PR TITLE
Update ru.xml

### PR DESCRIPTION
**Pull request by megafon929**
Russian new lines added

# WE MERGE PULL REQUESTS SUBMITTED HERE AFTER REVIEWED BY CORE DEVELOPER

If you are submitting any patches kindly wait for Core Developers to review.

You can join our community on Telegram
* [Community Group](https://t.me/pbrpcom)

* [Test Build & Build Help Group](https://t.me/pbrp_testers)

### CODE REVIEW

**Comment by manjotsidhu** [comment]
Are these changes tested ?

**Review by AndroiableDroid — APPROVED** [review]
LGTM

**Comment by megafon929** [comment]
Yes, it's better

**Comment by manjotsidhu** [comment]
Alright then, good to go

**Comment by manjotsidhu** [comment]
@megafon929 mind giving PR for the same for `android-10.0` ?

**Comment by megafon929** [comment]
Of course do it

**Pull request merged**
