### PR TITLE
Ameliorate English strings

### PR DESCRIPTION
**Pull request by LinkBoi00**
## We Merge Pull Requests Submitted Here After Reviewed By Core Developers

If you are submitting any patches, Tell us a little about it.

Fixes:
- Doesn't really fix anything in core functionality, it's more of an improvement rather than a fix

Improvements:
- Makes the recovery look a lot better by using more formal and grammatically correct language

Kindly wait for Core Developers to review.

### You can join our community on Telegram

- [Community Group](https://t.me/pbrpcom)
- [Test Build & Build Help Group](https://t.me/pbrp_testers)

### CODE REVIEW

**Comment by manjotsidhu** [comment]
@LinkBoi00 Can you send screenshot of the home screen with these changes ?

**Comment by LinkBoi00** [comment]
> @LinkBoi00 Can you send screenshot of the home screen with these changes ?

Sure
Screenshot_PBRP_2021-01-15-00-00-50
Screenshot_PBRP_2021-01-15-00-00-55
Screenshot_PBRP_2021-01-15-00-01-02

**Comment by Joker-V2** [comment]
@LinkBoi00

**Comment by LinkBoi00** [comment]
> @LinkBoi00

?

**Comment by DelightReza** [comment]
> > @LinkBoi00 Can you send screenshot of the home screen with these changes ?
> 
> Sure
> Screenshot_PBRP_2021-01-15-00-00-50
> Screenshot_PBRP_2021-01-15-00-00-55
> Screenshot_PBRP_2021-01-15-00-01-02

There should be Install ROM/Install Patches (Modify ROM)

**Comment by LinkBoi00** [comment]
> > > @LinkBoi00 Can you send screenshot of the home screen with these changes ?
> > 
> > 
> > Sure
> > Screenshot_PBRP_2021-01-15-00-00-50
> > Screenshot_PBRP_2021-01-15-00-00-55
> > Screenshot_PBRP_2021-01-15-00-01-02
> 
> There should be Install ROM/Install Patches (Modify ROM)

Is something like:
Install ROM or make modifications to the installed ROM (in 2 lines) fine?
(Maybe that won't fit, I'll work on it later today)

**Comment by LinkBoi00** [comment]
Screenshot_PBRP_2021-01-15-05-48-07 1

@md-raza I think that addresses your feedback. The previous string indicated that you cannot flash a new ROM, only make modifications to the existing one. I think that's fixed now

**Comment by LinkBoi00** [comment]
Also corrected a wrong capitalization in "Enable dmesg logging after flash" (F was capital)

**Comment by LinkBoi00** [comment]
@manjotsidhu Here's the final look of the home screen, adressing @md-raza 's feedback 

> Screenshot_PBRP_2021-01-15-05-48-07 1
> 
> @md-raza I think that addresses your feedback. The previous string indicated that you cannot flash a new ROM, only make modifications to the existing one. I think that's fixed now

So @manjotsidhu here's the final look of the home screen

**Comment by manjotsidhu** [comment]
> Screenshot_PBRP_2021-01-15-05-48-07 1
> 
> @md-raza I think that addresses your feedback. The previous string indicated that you cannot flash a new ROM, only make modifications to the existing one. I think that's fixed now

Actually the previous strings were made by @AndroiableDroid and he specifically made it to be in slang language. I don't know which is better. Would be needing community's feedback on this.

**Comment by LinkBoi00** [comment]
> > Screenshot_PBRP_2021-01-15-05-48-07 1
> > @md-raza I think that addresses your feedback. The previous string indicated that you cannot flash a new ROM, only make modifications to the existing one. I think that's fixed now
> 
> Actually the previous strings were made by @AndroiableDroid and he specifically made it to be in slang language. I don't know which is better. Would be needing community's feedback on this.

The thing is, that the language was inconsistent (for example, wrong capitalizations) and sometimes it was really not understandable, but sure, no problem. Thanks

**Comment by manjotsidhu** [comment]
Lets discuss on https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/discussions/66

**Comment by manjotsidhu** [comment]
> Lets discuss on #66

Looks like we have got sufficient feedback on it. @LinkBoi00 just need to change Advanced Card string to "More options for advanced users" and then we are good to go.

**Comment by AndroiableDroid** [comment]
@manjotsidhu LGTM

**Comment by LinkBoi00** [comment]
> > Lets discuss on #66
> 
> Looks like we have got sufficient feedback on it. @LinkBoi00 just need to change Advanced Card string to "More options for advanced users" and then we are good to go.

Alright, will do soon, thanks

**Comment by LinkBoi00** [comment]
It looks a bit empty w/o the second "more", maybe I will have to put something else in its place

**Comment by LinkBoi00** [comment]
@manjotsidhu Force pushed again, addressing your feedback

**Comment by LinkBoi00** [comment]
Also, I changed this string: pb_dmverity_chk, since, I think it's more understandable now

**Review by manjotsidhu — APPROVED** [review]

**Comment by manjotsidhu** [comment]
@AndroiableDroid once review for the final time.

**Comment by imranpopz** [comment]
> > > Screenshot_PBRP_2021-01-15-05-48-07 1
> > > @md-raza I think that addresses your feedback. The previous string indicated that you cannot flash a new ROM, only make modifications to the existing one. I think that's fixed now
> > 
> > 
> > Actually the previous strings were made by @AndroiableDroid and he specifically made it to be in slang language. I don't know which is better. Would be needing community's feedback on this.
> 
> The thing is, that the language was inconsistent (for example, wrong capitalizations) and sometimes it was really not understandable, but sure, no problem. Thanks

Is this the final homescreen ?

**Comment by manjotsidhu** [comment]
Almost, there is a small change in Advanced Card string

**Comment by imranpopz** [comment]
> Almost, there is a small change in Advanced Card string

Yup " More options for advanced users " suits better

**Comment by manjotsidhu** [comment]
@LinkBoi00 can you make PR for `android-10.0` branch as well ?

**Comment by LinkBoi00** [comment]
> @LinkBoi00 can you make PR for `android-10.0` branch as well ?

sure

**Pull request merged**
