### PR TITLE
PBRP: Unified  AB_OTA_UPDATER

### PR DESCRIPTION
**Pull request by hpnightowl**
It's already defined in Line 226, so why make another 'if' condition and add that cflag!

### CODE REVIEW

**Comment by manjotsidhu** [comment]
@hpnightowl you are good to merge.

**Comment by hpnightowl** [comment]
Don't Have permission to merge How Can i ?

**Comment by rokibhasansagar** [comment]
> Don't Have permission to merge How Can i ?

Allow me :smile:

**Comment by manjotsidhu** [comment]
@rokibhasansagar We have approved the PR, you have got permission to merge.

**Pull request merged**
